sudo: required

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

services:
  - docker

before_install:
  - cd docker
  - openssl aes-256-cbc -K $encrypted_64b32aabce5a_key -iv $encrypted_64b32aabce5a_iv -in awsDockerInstance.pem.enc -out awsDockerInstance.pem -d
  - cd ..

script:
  - sbt test
  - sbt clean dist
  - cp target/universal/project-1.0-SNAPSHOT.zip docker/project-1.0-SNAPSHOT.zip
  - cd docker
  - docker-compose up -d
  - cd ..
# Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push subin215/scala-project;
  - cd docker
  - chmod +x docker.sh
  - ./docker.sh
