sudo: required

language: scala

services:
  - docker

before_install:
  - sbt dist
# Docker builds steps need to furthur configured
#  - cd docker
#  - .\docker.sh
#
#after_success:
#  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#  - docker push subin215/scala-project;

