sudo: required

language: scala

services:
  - docker

before-install:
 - openssl aes-256-cbc -K $encrypted_64b32aabce5a_key -iv $encrypted_64b32aabce5a_iv -in testDockerInstance.pem.enc -out testDockerInstance.pem -d

script:
  - sbt dist
  - cd docker
  - ./docker.sh

