version: '2'
services:
  scalaproject:
    restart: unless-stopped
    build: .
    image: subin215/scala-project:1.0.1-SNAPSHOT
    ports:
      - "7000:9000"
    environment:
      DB_ADDRESS: advweb.cozoyl6zjpch.us-west-2.rds.amazonaws.com
      DB_USER: advWebProject
      DB_PASSWORD: ChciJgYZNaL7
